use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct AspectDegreesConfig {
    #[serde(default)]
    aspect_degrees: BTreeMap<String, f64>,
}

#[derive(Debug, Deserialize)]
struct OrbDegreesConfig {
    #[serde(default)]
    orb_degrees: BTreeMap<String, f64>,
}

fn read_to_string(path: &Path) -> String {
    fs::read_to_string(path).unwrap_or_else(|e| panic!("Failed to read {}: {e}", path.display()))
}

fn ensure_non_empty_map(source: &str, name: &str, map: &BTreeMap<String, f64>) {
    if map.is_empty() {
        panic!("{name} was empty in {source}");
    }
}

fn generate_constants_rs(
    aspect_cfg: &AspectDegreesConfig,
    aspect_toml_rel_path: &str,
    orb_cfg: &OrbDegreesConfig,
    orb_toml_rel_path: &str,
) -> String {
    let mut out = String::new();

    out.push_str("// @generated by build.rs\n");
    out.push_str("//\n");
    out.push_str("// Sources:\n");
    out.push_str("// - ");
    out.push_str(aspect_toml_rel_path);
    out.push('\n');
    out.push_str("// - ");
    out.push_str(orb_toml_rel_path);
    out.push('\n');
    out.push_str("//\n");
    out.push_str("// DO NOT EDIT BY HAND. Edit the TOML instead.\n\n");

    out.push_str("// Aspect degrees\n");
    for (k, v) in &aspect_cfg.aspect_degrees {
        // Keep output stable and obvious.
        // Always print with a decimal point so `0` becomes `0.0` (and thus type-checks as `f64`).
        out.push_str("pub const ");
        out.push_str(k);
        out.push_str(": f64 = ");
        out.push_str(&format!("{v:.10}"));
        out.push_str(";\n");
    }

    out.push_str("\n// ORB DEFAULTS\n");
    for (k, v) in &orb_cfg.orb_degrees {
        out.push_str("pub const ");
        out.push_str(k);
        out.push_str(": f64 = ");
        out.push_str(&format!("{v:.10}"));
        out.push_str(";\n");
    }

    out
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));

    let aspect_config_rel_path = PathBuf::from("config/aspect_degrees.toml");
    let orb_config_rel_path = PathBuf::from("config/orb_degrees.toml");

    let aspect_config_path = manifest_dir.join(&aspect_config_rel_path);
    let orb_config_path = manifest_dir.join(&orb_config_rel_path);

    // Ensure Cargo rebuilds when the config changes.
    println!(
        "cargo:rerun-if-changed={}",
        aspect_config_rel_path.display()
    );
    println!("cargo:rerun-if-changed={}", orb_config_rel_path.display());

    let aspect_toml_str = read_to_string(&aspect_config_path);
    let aspect_cfg: AspectDegreesConfig = toml::from_str(&aspect_toml_str)
        .unwrap_or_else(|e| panic!("Failed to parse {}: {e}", aspect_config_rel_path.display()));

    let orb_toml_str = read_to_string(&orb_config_path);
    let orb_cfg: OrbDegreesConfig = toml::from_str(&orb_toml_str)
        .unwrap_or_else(|e| panic!("Failed to parse {}: {e}", orb_config_rel_path.display()));

    ensure_non_empty_map(
        &aspect_config_rel_path.to_string_lossy(),
        "aspect_degrees",
        &aspect_cfg.aspect_degrees,
    );
    ensure_non_empty_map(
        &orb_config_rel_path.to_string_lossy(),
        "orb_degrees",
        &orb_cfg.orb_degrees,
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let generated_path = out_dir.join("aspect_constants_generated.rs");

    let rs = generate_constants_rs(
        &aspect_cfg,
        &aspect_config_rel_path.to_string_lossy(),
        &orb_cfg,
        &orb_config_rel_path.to_string_lossy(),
    );

    fs::write(&generated_path, rs)
        .unwrap_or_else(|e| panic!("Failed to write {}: {e}", generated_path.display()));
}
