[symbols]
Sun = "☉"
Moon = "☽"
Mercury = "☿"
Venus = "♀"
Mars = "♂"
Jupiter = "♃"
Saturn = "♄"
Uranus = "♅"
Neptune = "♆"
Pluto = "♇"
Chiron = "⚷"
Ceres = "⚳"
Pallas = "⚴"
Juno = "⚵"
Vesta = "⚶"
Eris = "⯰"
Makemake = "⯱"
Haumea = "⯲"
Sedna = "⯳"
Quaoar = "⯴"
Hygiea = "⯚"
Nessus = "⯜"

